let photoQueue=Promise.resolve(),photoPauseUntil=0,photoLastAt=0;
function photoGet(url){const job=photoQueue.then(async()=>{if(Date.now()<photoPauseUntil)throw Error('Photo service cooldown');const delay=Math.max(0,400-(Date.now()-photoLastAt));if(delay)await new Promise(r=>setTimeout(r,delay));photoLastAt=Date.now();try{return await jget(url);}catch(e){if(/429|503/.test(e.message))photoPauseUntil=Date.now()+60000;throw e;}});photoQueue=job.catch(()=>{});return job;}
/* Every attraction uses the same identity and metadata checks. No nearby-photo fallback. */
const PHOTO_REJECT=/噴煙|噴火|案内板|銘板|説明板|看板|地図|配置図|平面図|路線図|古写真|絵葉書|絵はがき|浮世絵|肖像|モノクロ|eruption|smoke|ash[ _-]*cloud|steam[ _-]*plume|signboard|information[ _-]*board|close[ _-]*up|detail[ _-]*of|portraits?|postcards?|engravings?|lithographs?|monochrome|black[ _-]*and[ _-]*white|floor[ _-]*plan|\b(?:maps?|logos?|flags?|diagrams?|paintings?|drawings?|illustrations?|fog|clouds?)\b/i;
const PHOTO_WIDE=/全景|遠景|全体|外観|正面|正門|庭園|境内|本堂|本殿|風景|panoram|overall|exterior|facade|landscape|general[ _-]*view/i;
const attractionArticleCache=new Map();
function attractionText(x){return String(x||'').normalize('NFKC').replace(/<[^>]*>/g,' ').replace(/[_\s]+/g,' ').trim();}
function attractionCore(x){return attractionText(x).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').normalize('NFKC').toLowerCase().replace(/[\s・ー‐\-（）()]/g,'');}
titleCands=function(name){const n=String(name).trim(),b=n.replace(/（.*?）|\(.*?\)/g,'').trim();return [...new Set([n,b].filter(Boolean))];};
function attractionNames(o,p){return [...new Set([...titleCands(o.name),p?.title,...(p?.langlinks||[]).map(x=>x.title)].filter(Boolean))];}
function attractionNameIn(text,names){const t=attractionCore(text);return names.some(n=>{const k=attractionCore(n);return k.length>=2&&t.includes(k);});}
function attractionPosition(o,p){const c=p?.coordinates?.[0];return !!c&&bookingPoint(o)&&hav(o,{lat:c.lat,lng:c.lon})<(/山|湖|島|渓谷|渓流|国立公園/.test(o.name)?12:3);}
function attractionPhotoScore(p,o,article){const ii=p.imageinfo?.[0];if(!ii||!/^image\/(jpeg|png|webp)$/.test(ii.mime||'')||ii.width<600||ii.height<350)return null;const ratio=ii.width/ii.height;if(ratio<0.6||ratio>3)return null;const m=ii.extmetadata||{},caption=attractionText(m.ImageDescription?.value),text=attractionText(p.title+' '+caption+' '+(m.Categories?.value||''));const from=caption.match(/(.{1,50})から(?:見た|望む)/);if(from&&!/展望|山|岬|峠/.test(o.name)&&attractionNameIn(from[1],[o.name]))return null;if(BADIMG.test(p.title)||OLDIMG.test(p.title)||PHOTO_REJECT.test(text)||!attractionNameIn(p.title+' '+caption,attractionNames(o,article)))return null;const file=p.title.replace(/^(?:File|ファイル):/i,'');return {file,...fromInfo(ii,p.title,false),score:(PHOTO_WIDE.test(text)?20:0)+(attractionCore(file)===attractionCore(article?.pageimage)?6:0)+(ratio>=1.3&&ratio<=2.3?3:0)+Math.min(4,ii.width/1000),contain:ratio<1.1,lazyCredit:false,policy:7};}
async function attractionCandidates(o,article){
 let names=[article.pageimage,...(article.images||[]).map(x=>x.title.replace(/^(?:File|ファイル):/i,''))].filter(x=>x&&/\.(jpe?g|png|webp)$/i.test(x)&&!BADIMG.test(x)&&!OLDIMG.test(x));
 // The multi-article API applies image limits across the batch: fetch this article's alternatives if missing.
 if(names.length<2){const j=await photoGet(WP+'action=query&prop=images&imlimit=40&titles='+enc(article.title));names.push(...(j.query?.pages?.[0]?.images||[]).map(x=>x.title.replace(/^(?:File|ファイル):/i,'')));}
 names=[...new Set(names)].sort((a,b)=>((attractionNameIn(b,attractionNames(o,article))?20:0)+(PHOTO_WIDE.test(b)?10:0)+(b===article.pageimage?6:0))-((attractionNameIn(a,attractionNames(o,article))?20:0)+(PHOTO_WIDE.test(a)?10:0)+(a===article.pageimage?6:0))).filter(x=>/\.(jpe?g|png|webp)$/i.test(x)&&!BADIMG.test(x)&&!OLDIMG.test(x)).slice(0,6);if(!names.length)return [];
 const j=await photoGet(CM+'action=query&prop=imageinfo&iiprop=url|extmetadata|mime|size&iiurlwidth=500&titles='+enc(names.map(n=>'File:'+n).join('|')));
 return (j.query?.pages||[]).map(p=>attractionPhotoScore(p,o,article)).filter(Boolean).sort((a,b)=>b.score-a.score);
}
async function attractionArticles(items){const titles=[...new Set(items.flatMap(x=>titleCands(x.o.name)))],pages={};for(let i=0;i<titles.length;i+=40){const chunk=titles.slice(i,i+40),j=await photoGet(WP+'action=query&redirects=1&prop=pageimages|coordinates|langlinks&piprop=name&pilicense=free&pilimit=50&colimit=50&imlimit=12&lllang=en&lllimit=50&titles='+enc(chunk.join('|'))),q=j.query||{},map={};chunk.forEach(t=>map[t]=t);for(const x of [...(q.normalized||[]),...(q.redirects||[])])for(const t of Object.keys(map))if(map[t]===x.from)map[t]=x.to;const byTitle=Object.fromEntries((q.pages||[]).filter(p=>!p.missing).map(p=>[p.title,p]));chunk.forEach(t=>{if(byTitle[map[t]])pages[t]=byTitle[map[t]];});}for(const {k,o} of items)attractionArticleCache.set(k,titleCands(o.name).map(t=>pages[t]).find(p=>p&&attractionPosition(o,p))||null);}
function curatedAttraction(o){return o&&norm(o.name)==='桜島'&&bookingPoint(o)&&hav(o,{lat:31.585,lng:130.657})<12?{file:'Sakurajima -城山展望台より.jpg',src:new URL('booking/assets/sakurajima.jpg',document.baseURI).href,artist:'こたつむり / 露出調整 Nkon21',license:'CC BY-SA 2.1 JP',page:'https://commons.wikimedia.org/wiki/File:Sakurajima_-%E5%9F%8E%E5%B1%B1%E5%B1%95%E6%9C%9B%E5%8F%B0%E3%82%88%E3%82%8A.jpg'}:null;}
runBatch=async function(){const keys=[...batchQ];batchQ.clear();if(!keys.length)return;const items=keys.map(k=>({k,o:IMGREG[k]})).filter(x=>x.o&&!x.o.food&&!x.o.hotel&&!curatedAttraction(x.o));try{await attractionArticles(items);}catch(e){}for(const k of keys)imgQueue.push(k);pumpImg();};
findImage=async function(o){if(!o||o.food||o.hotel)return {none:true,t:Date.now()};const c=curatedAttraction(o);if(c)return {...c,lazyCredit:false,near:false,policy:7};try{const k=imgKey(o);if(!attractionArticleCache.has(k))await attractionArticles([{k,o}]);const article=attractionArticleCache.get(k);if(!article)return {none:true,t:Date.now(),unverified:true};const list=await attractionCandidates(o,article);return list.length?{...list[0],alts:list.map(r=>({...r})),ai:0}:{none:true,t:Date.now(),unverified:true};}catch(e){return {none:true,t:Date.now(),err:true};}};
altPhotos=async function(k){const o=IMGREG[k];if(!o||o.food||o.hotel)return [];if(IMG[k]?.alts)return IMG[k].alts;return (await findImage(o))?.alts||[];};
nextPhoto=async function(k){const list=await altPhotos(k);if(list.length<2){toast('対象の場所と景観を確認できる別の写真が見つかりませんでした');return;}const i=((IMG[k]?.ai??0)+1)%list.length;IMG[k]={...list[i],alts:list,ai:i,near:false};imgSave();paintKey(k);};
const attractionInner=phInner;phInner=function(k,size){return attractionInner(k,size).replace('<img ',IMG[k]?.contain?'<img style="object-fit:contain;background:#edf2f5" ':'<img ').replace('写真が見つかりませんでした',IMG[k]?.unverified?'この観光地の写真は未確認です':'写真が見つかりませんでした');};
const attractionRetry=retryImages;retryImages=function(){attractionArticleCache.clear();attractionRetry();};
